### ISSUE TITLE
AdbClient.Instance.Install() fails if apk is already installed

### ISSUE THREAD

**Issue by the1337moderator** [quamotion/madb#123]
When attempting to use `AdbClient.Instance.Install()` with an APK that is already installed on the target device, a `SharpAdbClient.Exceptions.AdbException` is received. 

Possible solution:
Check if already installed, have a bool flag as function parameter to determine if it should be skipped or should be uninstalled/installed

Calling code:
```csharp
foreach (FileInfo apkFile in new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, "Resources\\apk")).GetFiles("*.apk").ToList())
{
    Console.Write($"Installing Package:{apkFile.Name}");
    using (FileStream fs = new FileStream(apkFile.FullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
    {
        try
        {
            AdbClient.Instance.Install(device, fs);  // Exception thrown if already installed.
            Console.WriteLine("     Done.");
        }
        catch (SharpAdbClient.Exceptions.AdbException ex) { Console.WriteLine("     Failed" + ex.Message); }
    }
}
```

Exception data:
> SharpAdbClient.Exceptions.AdbException
>   HResult=0x80131500
>   Message=Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.adobe.reader without first uninstalling.]
>   Source=SharpAdbClient
>   StackTrace:
>    at SharpAdbClient.AdbClient.Install(DeviceData device, Stream apk, String[] arguments)
>    at TabletPrep.Program.Main(String[] args) in \source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 102

**Comment by kluivert-queiroz** [comment]
If someone still suffering with something similar, the solution is pass **-r** parameter to the requestBuilder inside AdbClient class.

This will make the app reinstall if needed, it's defined in ADB documentation.

Example:
`AdbClient.Instance.install(device, stream, new string[] {"-r"};`
