### ISSUE TITLE
INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by michaeled** [quamotion/madb#38]
I apologize for the lack of information, but I'm attempting to install a package that's on my desktop to the android simulator. This is half of the stack trace from the PackageInstallationException. Any thoughts?

at SharpAdbClient.DeviceCommands.PackageManager.InstallRemotePackage(String remoteFilePath, Boolean reinstall) in C:\projects\madb\SharpAdbClient\DeviceCommands\PackageManager.cs:line 137
   at SharpAdbClient.DeviceCommands.PackageManager.InstallPackage(String packageFilePath, Boolean reinstall) in C:\projects\madb\SharpAdbClient\DeviceCommands\PackageManager.cs:line 116

**Comment by michaeled** [comment]
Pushing the apk to /data/local/tmp and then installing the package using PackageManager.InstallRemotePackage resolved my issue.
